name: Test Jackdaw

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Preinstall Torch to avoid issue in Torch-Sparse
          pip install torch
          pip install ".[all]"
      - name: Test with pytest
        env:
          SHAREABLEAI_TEST_API_KEY: ${{ secrets.SHAREABLEAI_TEST_API_KEY }}
        run: |
          pytest
          
  publish:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         python -m pip install --upgrade setuptools wheel
         pip install .
      - name: Upload to PyPi
        env:
         TWINE_USERNAME: '__token__'
         TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
         python setup.py bdist_wheel
         python -m pip install -U twine
         twine upload -u $TWINE_USERNAME -p $TWINE_PASSWORD dist/*.whl
